# ======================================================
# Hexion Configuration
# ======================================================

# ======================================================
# General Configurations
# ======================================================
[general]
siteName = "Hexion"
domain = "https://hexion.dev"
port = 3000
onMaintenance = false
version = "1.0.0-demo"