# ======================================================
# Hexion Configuration
# ======================================================

# ======================================================
# General Configurations
# ======================================================

[general]
siteName = "Hexion"
domain = "https://hexion.dev"
port = 7000
onMaintenance = false
version = "v1.0.0-demo"