# ======================================================
# Hexion Configuration
# ======================================================

# ======================================================
# General Configurations
# ======================================================
[general]
siteName = "SiteName"
domain = "https://example.com"
port = 7000
onMaintenance = false
version = "1.0.0-demo"