name: Continue Push Integration

on:
  push:
    branches: [ v1 ]

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 24
      - run: npm ci
      - run: nohup npm start &
      - run: npm test